### ISSUE TITLE
Nest Doorbell Camera

### ISSUE THREAD

**Issue by andreas-fahrecker** [n0rt0nthec4t/homebridge-nest-accfactory#11]
When I try to access my Nest Doorbell (wired) homebridge crashes.

I can see the Video feed in the small Preview in the home app. but when I click on it to see it in fullscreen it crashes.

I get the following log:

```
[12/9/2024, 8:52:44 PM] TypeError: Asynchronous forks do not support Buffer, TypedArray, DataView or string input: ''
    at new NodeError (node:internal/errors:405:5)
    at node:internal/child_process:1061:15
    at Array.reduce (<anonymous>)
    at getValidStdio (node:internal/child_process:991:11)
    at ChildProcess.spawn (node:internal/child_process:355:11)
    at Object.spawn (node:child_process:757:9)
    at NestDoorbell.handleStreamRequest (file:///usr/lib/node_modules/homebridge-nest-accfactory/dist/camera.js:807:43)
    at RTPStreamManagement._handleStartStream (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1029:19)
    at RTPStreamManagement._handleSelectedStreamConfigurationWrite (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:853:12)
    at SelectedRTPStreamConfiguration.emit (node:events:514:28)
[12/9/2024, 8:52:44 PM] Got SIGTERM, shutting down Homebridge...
```

From what I can see the issue either is caused by the `camera.js` or by the `hap-nodejs ` dependency, from what I see, if the issue comes from the dependency, the relevant code from the GitHub repository is in the [src/lib/camera/RTPStreamManagement.ts](https://github.com/homebridge/HAP-NodeJS/blob/791c3619ceff6ca395b819a7afe13590a76c5405/src/lib/camera/RTPStreamManagement.ts) at a previous commit, because it seems like the code changed since 1.1.1-beta.7

**Comment by andreas-fahrecker** [comment]
I am running a [Docker-Container](https://github.com/SiwatINC/homebridge_gui) from the unraid App Library. 

OS: Ubuntu 22.04.1 LTS (Jammy)
node: v18.17.1
homebridge: 1.8.5
homebridge-nest-accfactory: 0.2.3

**Comment by n0rt0nthec4t** [comment]
OK, have been able to replicate it. Seems I've missed something (silly error) when you have audio disabled. I'll work on a fix and it will be pushed later today in 0.2.4 of the plugin. Appreciate you reporting this and allowing me to fix it! :-)

**Comment by n0rt0nthec4t** [comment]
fix included in https://github.com/n0rt0nthec4t/homebridge-nest-accfactory/releases/tag/0.2.4

**Comment by andreas-fahrecker** [comment]
Well, I had to update my docker-container because now I wouldn't load the plugin with node 18. Now with Node 20 the plugin loads again.
But the camera stream still doesn't work. It did improve, by not crashing the homebridge anymore. However the stream still fails.

```
[12/10/2024, 4:11:25 PM] [NestAccfactory] Live stream started on "Nest Doorbell" 
[12/10/2024, 4:11:25 PM] [NestAccfactory] ffmpeg video/audio live streaming process for "Nest Doorbell" stopped unexpectedly. Exit code was "1"
[12/10/2024, 4:11:25 PM] [NestAccfactory] Live stream stopped from "Nest Doorbell"
```

**Comment by n0rt0nthec4t** [comment]
Are you using the offical homebridge docker container or own made one?
Can you run homebridge in debug mode, and paste that output here? 
Where did the ffmpeg binary come from?

**Comment by andreas-fahrecker** [comment]
I am not using the official homebridge docker container, I am now using my own that I forked from the one in the unraid App Library. The only modification I made being to use node 20 instead of node 18.


Homebridge log in debug mode:
```
[12/10/2024, 8:48:18 PM] [NestAccfactory] ffmpeg process for live streaming from "Nest Doorbell" will be called using the following commandline -hide_banner -nostats -use_wallclock_as_timestamps 1 -fflags +discardcorrupt -max_delay 500000 -flags low_delay -f h264 -i pipe:0 -map 0:v:0 -codec:v copy -fps_mode passthrough -reset_timestamps 1 -video_track_timescale 90000 -payload_type 99 -ssrc 9275579 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params mMI9tzROUfwfMKSOaf1rIS1Bu6byZFzaZ0Z7knck srtp://10.15.6.2:53476?rtcpport=53476&pkt_size=1378
[12/10/2024, 8:48:18 PM] [NestAccfactory] Live stream started on "Nest Doorbell" 
[12/10/2024, 8:48:18 PM] [NestAccfactory] Connection started to "oculus196-eu1.dropcam.com"
[12/10/2024, 8:48:18 PM] [NestAccfactory] Started live stream from uuid "quartz.f309a9d4e2014b5f9004daf7681a0ea8" and sesssion id of "81198d40-a440-4420-8123-25b2b681f7cf"
[12/10/2024, 8:48:18 PM] [NestAccfactory] Unrecognized option 'fps_mode'.
Error splitting the argument list: Option not found

[12/10/2024, 8:48:18 PM] [NestAccfactory] ffmpeg video/audio live streaming process for "Nest Doorbell" stopped unexpectedly. Exit code was "1"
[12/10/2024, 8:48:18 PM] [NestAccfactory] Stopped live stream from uuid "quartz.f309a9d4e2014b5f9004daf7681a0ea8"
[12/10/2024, 8:48:18 PM] [NestAccfactory] Live stream stopped from "Nest Doorbell"
[12/10/2024, 8:48:18 PM] [NestAccfactory] Connection closed to "oculus196-eu1.dropcam.com"
```

ffmpeg comes from the ubuntu apt repo:
```
# apt list --installed | grep ffmpeg

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ffmpeg/jammy-updates,jammy-security,now 7:4.4.2-0ubuntu0.22.04.1 amd64 [installed]
# ffmpeg
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
# 
```

**Comment by n0rt0nthec4t** [comment]
ok.. you need an ffmpeg binary which is version 6 or later. I had a check in code for that version, but maybe how the version string is display doesn't work correctly.

**Comment by andreas-fahrecker** [comment]
Thanks.

I added ffmpeg-for-homebridge to my container and now it works.

**Comment by n0rt0nthec4t** [comment]
Great to hear. I'l close this issue now as resolved
